### ISSUE TITLE
Support for multiple icons

### ISSUE THREAD

**Issue by lucasschonrock** [GioPan04/flutter_icon_switcher#2]
Been looking for  a icon switcher for flutter for a long time, so this looks great. Planning on adding support for multiple icons anytime soon?

**Comment by GioPan04** [comment]
Hi, this package will be merged into [tastelessjolt/flutter_dynamic_icon](https://github.com/tastelessjolt/flutter_dynamic_icon) to add iOS support and multiple icons for Android. I made a [pull](https://github.com/tastelessjolt/flutter_dynamic_icon/pull/10) into that repo but hasn't been merged yet. If you want to try it you can use [this](https://github.com/GioPan04/flutter_dynamic_icon/tree/android-support) repo
