### ISSUE TITLE
App closes on icon set

### ISSUE THREAD

**Issue by lucasschonrock** [GioPan04/flutter_icon_switcher#3]
The app closes immediately upon setting the icon and label. I don't know if this is just an android limitation, or actually a bug?. It does set the icon and label successfully though.

**Comment by GioPan04** [comment]
Hi,
This plugin will be merged into [flutter_dynamic_icon](https://github.com/tastelessjolt/flutter_dynamic_icon) and I will no more update this plugin.
This is a normal behavior, since to update the icon replace the current activity with a new one with the new icon/label.
